In [2]:
# nbi:hide_in
import matplotlib.pyplot as plt
import numpy as np
import ipywidgets as widgets

%matplotlib inline

In [214]:
# nbi:hide_in

from numpy.random import default_rng


def random_dice(seed,size):
    rng = default_rng(seed)
    rolls = rng.choice([1,2,3,4,5,6], size=size);
    averages = np.cumsum(rolls) / np.arange(1,size+1);
    return [rolls,averages]

[rolls,averages]= random_dice(1234,1000)

def plotting_dice(num_rolls):
    fig, ax = plt.subplots(figsize=(12, 6))
    plt.rcParams.update({'font.size': 20})
    plt.ylim([0, 7])
    
    
    plt.xlim([1,100])
    if num_rolls>100:
        plt.xlim([1,num_rolls])
    ax.text(1.5, 3.55,"$\mu$")

    plt.ylabel("Mittelwert der Augenzahl")
    plt.plot(np.arange(1,1000+1)[:num_rolls],averages[:num_rolls],'-',linewidth=3)
    plt.plot(np.arange(1,1000+1)[:num_rolls],averages[:num_rolls],'x',linewidth=5)
    plt.plot([0, 1000], [7/2, 7/2], 'r', linewidth=2)
    plt.xlabel("Anzahl der Würfe")
    

In [215]:
# nbi:hide_in
widgets.interact(plotting_dice,num_rolls=IntSlider(description="#Würfe", min=2,max=1000,value=2));

interactive(children=(IntSlider(value=2, description='#Würfe', max=1000, min=2), Output()), _dom_classes=('wid…

In [211]:
import ipywidgets as widgets
from ipywidgets import interact, interact_manual, IntSlider

def f(x):
    return x;

interact(f, x=IntSlider(description="#Würfe", min=1,max=100,value=1));

interactive(children=(IntSlider(value=1, description='#Würfe', min=1), Output()), _dom_classes=('widget-intera…

In [59]:
from numpy.random import Generator, MT19937, SeedSequence
sg = SeedSequence(1234)
rg = [Generator(MT19937(s)) for s in sg.spawn(10)]

In [60]:
np.random.choice([1,2,3,4,5,6],size=10)

array([1, 5, 1, 4, 5, 1, 6, 5, 6, 6])

In [61]:
from numpy.random import default_rng
rng = default_rng()
vals = rng.standard_normal(10)
more_vals = rng.standard_normal(10)

In [62]:
vals

array([-1.01457545, -0.28714973, -0.7159295 ,  1.48406525,  2.05467343,
       -0.7399317 , -1.43701208,  0.25141865,  0.41288655,  0.49436998])

array([5, 2, 5, 2, 2, 5, 4, 5, 6, 3])

In [92]:
print(rng)


Generator(PCG64)


In [93]:
print(rng.random())

0.22733602246716966


In [94]:
print(rng.random())

0.31675833970975287


In [95]:
rng.random.choice([1,2,3,4,5,6])

AttributeError: 'builtin_function_or_method' object has no attribute 'choice'

array([2, 5, 1, 3, 1, 5, 3, 3, 3, 3])